part of social_blogging;

// http://www.json.org/
// http://jsonformatter.curiousconcept.com/

// lib/social/blogging/json/model.dart

var socialBloggingModelJson = r'''
{
    "width":990,
    "height":580,
    "boxes":[
        {
            "name":"Blog",
            "entry":true,
            "x":81,
            "y":65,
            "width":60,
            "height":100,
            "items":[
                {
                    "sequence":10,
                    "name":"link",
                    "category":"identifier",
                    "type":"Uri",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":20,
                    "name":"name",
                    "category":"required",
                    "type":"String",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":30,
                    "name":"privacy",
                    "category":"attribute",
                    "type":"String",
                    "init":"public",
                    "essential":false,
                    "sensitive":false
                },
                {
                    "sequence":40,
                    "name":"language",
                    "category":"attribute",
                    "type":"String",
                    "init":"English",
                    "essential":false,
                    "sensitive":false
                }
            ]
        },
        {
            "name":"Article",
            "entry":false,
            "x":321,
            "y":68,
            "width":80,
            "height":120,
            "items":[
                {
                    "sequence":10,
                    "name":"title",
                    "category":"identifier",
                    "type":"String",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":20,
                    "name":"content",
                    "category":"required",
                    "type":"String",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                },
                {
                    "sequence":30,
                    "name":"creationDate",
                    "category":"attribute",
                    "type":"DateTime",
                    "init":"now",
                    "essential":false,
                    "sensitive":false
                },
                {
                    "sequence":40,
                    "name":"medium",
                    "category":"attribute",
                    "type":"String",
                    "init":"text",
                    "essential":false,
                    "sensitive":false
                },
                {
                    "sequence":50,
                    "name":"plus",
                    "category":"attribute",
                    "type":"int",
                    "init":"0",
                    "essential":false,
                    "sensitive":false
                },
                {
                    "sequence":60,
                    "name":"minus",
                    "category":"attribute",
                    "type":"int",
                    "init":"0",
                    "essential":false,
                    "sensitive":false
                }
            ]
        },
        {
            "name":"User",
            "entry":true,
            "x":95,
            "y":312,
            "width":100,
            "height":100,
            "items":[
                {
                    "sequence":10,
                    "name":"name",
                    "category":"identifier",
                    "type":"String",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":20,
                    "name":"password",
                    "category":"required",
                    "type":"String",
                    "init":"",
                    "essential":false,
                    "sensitive":true
                },
                {
                    "sequence":30,
                    "name":"email",
                    "category":"required",
                    "type":"String",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":40,
                    "name":"registrationDate",
                    "category":"attribute",
                    "type":"DateTime",
                    "init":"now",
                    "essential":false,
                    "sensitive":false
                }
            ]
        },
        {
            "name":"Category",
            "entry":true,
            "x":445,
            "y":67,
            "width":80,
            "height":60,
            "items":[
                {
                    "sequence":10,
                    "name":"name",
                    "category":"identifier",
                    "type":"String",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                }
            ]
        },
        {
            "name":"Tag",
            "entry":false,
            "x":556,
            "y":249,
            "width":60,
            "height":60,
            "items":[
                
            ]
        },
        {
            "name":"Comment",
            "entry":true,
            "x":451,
            "y":329,
            "width":80,
            "height":80,
            "items":[
                {
                    "sequence":10,
                    "name":"text",
                    "category":"required",
                    "type":"String",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                },
                {
                    "sequence":20,
                    "name":"date",
                    "category":"attribute",
                    "type":"DateTime",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":30,
                    "name":"by",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                }
            ]
        },
        {
            "name":"Following",
            "entry":false,
            "x":366,
            "y":222,
            "width":80,
            "height":80,
            "items":[
                {
                    "sequence":10,
                    "name":"date",
                    "category":"attribute",
                    "type":"DateTime",
                    "init":"now",
                    "essential":false,
                    "sensitive":false
                }
            ]
        }
    ],
    "lines":[
        {
            "box1Name":"Blog",
            "box2Name":"Article",
            "category":"relationship",
            "internal":true,
            "box1box2Name":"articles",
            "box1box2Min":"0",
            "box1box2Max":"N",
            "box1box2Id":false,
            "box2box1Name":"blog",
            "box2box1Min":"1",
            "box2box1Max":"1",
            "box2box1Id":true
        },
        {
            "box1Name":"User",
            "box2Name":"Blog",
            "category":"relationship",
            "internal":false,
            "box1box2Name":"blogs",
            "box1box2Min":"0",
            "box1box2Max":"N",
            "box1box2Id":false,
            "box2box1Name":"user",
            "box2box1Min":"1",
            "box2box1Max":"1",
            "box2box1Id":false
        },
        {
            "box1Name":"Article",
            "box2Name":"Tag",
            "category":"relationship",
            "internal":true,
            "box1box2Name":"tags",
            "box1box2Min":"0",
            "box1box2Max":"N",
            "box1box2Id":false,
            "box2box1Name":"article",
            "box2box1Min":"1",
            "box2box1Max":"1",
            "box2box1Id":false
        },
        {
            "box1Name":"Category",
            "box2Name":"Tag",
            "category":"relationship",
            "internal":false,
            "box1box2Name":"tags",
            "box1box2Min":"0",
            "box1box2Max":"N",
            "box1box2Id":false,
            "box2box1Name":"category",
            "box2box1Min":"1",
            "box2box1Max":"1",
            "box2box1Id":true
        },
        {
            "box1Name":"User",
            "box2Name":"Following",
            "category":"twin",
            "internal":true,
            "box1box2Name":"follows",
            "box1box2Min":"0",
            "box1box2Max":"N",
            "box1box2Id":false,
            "box2box1Name":"followedBy",
            "box2box1Min":"1",
            "box2box1Max":"1",
            "box2box1Id":true
        },
        {
            "box1Name":"User",
            "box2Name":"Following",
            "category":"twin",
            "internal":false,
            "box1box2Name":"followedBy",
            "box1box2Min":"0",
            "box1box2Max":"N",
            "box1box2Id":false,
            "box2box1Name":"follows",
            "box2box1Min":"1",
            "box2box1Max":"1",
            "box2box1Id":true
        }
    ]
}
''';
  