name: social_blogging
version: 0.0.6
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: social_blogging application that uses dartling for its model.
homepage: http://ondart.me/
environment:
  sdk: '>=0.8.10+8 <2.0.0'
documentation: http://goo.gl/TRRb0e
dependencies:
  browser: '>=0.9.0 <0.10.0'
  dartling: '>=2.0.0 <3.0.0'
  dartling_default_app: '>=1.0.5 <2.0.0'
