name: social_blogging
author: Dzenan Ridjanovic
homepage: http://ondart.me/
version: 0.0.1
description: social_blogging application that uses dartling for its model.
environment:
  sdk: '>=1.9.3 <2.0.0'
dependencies:
  browser: any
  dartling:
    git: git://github.com/dzenanr/dartling.git
  dartling_default_app:
    git: git://github.com/dzenanr/dartling_default_app.git
  